/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 13.0.2
board: MIMXRT1010-EVK
pin_labels:
- {pin_num: '3', pin_signal: GPIO_09, label: 'LPUART1_RXD/J56[2]', identifier: UART1_RXD}
- {pin_num: '2', pin_signal: GPIO_10, label: 'LPUART1_TXD/J56[4]', identifier: UART1_TXD}
- {pin_num: '65', pin_signal: GPIO_SD_10, label: 'FlexSPI_CLK_A/U13[6]', identifier: FlexSPI_CLK}
- {pin_num: '66', pin_signal: GPIO_SD_09, label: 'FlexSPI_D0_A/U13[5]', identifier: FlexSPI_D0_A}
- {pin_num: '68', pin_signal: GPIO_SD_07, label: 'FlexSPI_D1_A/U13[2]', identifier: FlexSPI_D1_A}
- {pin_num: '67', pin_signal: GPIO_SD_08, label: 'FlexSPI_D2_A/U13[3]', identifier: FlexSPI_D2_A}
- {pin_num: '64', pin_signal: GPIO_SD_11, label: 'FlexSPI_D3_A/U13[7]', identifier: FlexSPI_D3_A}
- {pin_num: '69', pin_signal: GPIO_SD_06, label: 'FlexSPI_SS0/U13[1]', identifier: FlexSPI_SS0}
- {pin_num: '1', pin_signal: GPIO_11, label: GPIO_11, identifier: GPIO_11}
- {pin_num: '70', pin_signal: GPIO_SD_05, label: USER_BUTTON, identifier: USER_BUTTON}
- {pin_num: '11', pin_signal: GPIO_02, label: 'I2C1_SCL/U10[17]/J57[20]/U26[4]', identifier: I2C1_SCL}
- {pin_num: '12', pin_signal: GPIO_01, label: 'I2C1_SDA/U10[18]/J57[18]/U26[6]', identifier: I2C1_SDA}
- {pin_num: '7', pin_signal: NVCC_GPIO_1, label: NVCC_GPIO_3V3}
- {pin_num: '50', pin_signal: NVCC_GPIO_2, label: NVCC_GPIO_3V3}
- {pin_num: '63', pin_signal: NVCC_GPIO_3, label: NVCC_GPIO_3V3}
- {pin_num: '71', pin_signal: NVCC_GPIO_4, label: NVCC_GPIO_3V3}
- {pin_num: '16', pin_signal: VSS_1, label: GND}
- {pin_num: '20', pin_signal: DCDC_GND, label: GND}
- {pin_num: '30', pin_signal: VSS_2, label: GND}
- {pin_num: '54', pin_signal: VSS_3, label: GND}
- {pin_num: '78', pin_signal: VSS_4, label: GND}
- {pin_num: '23', pin_signal: TEST_MODE, label: GND}
- {pin_num: '26', pin_signal: VDD_SNVS_CAP, label: GND}
- {pin_num: '14', pin_signal: VDD_SOC_IN/DCDC_SENSE, label: VDD_SOC_IN/DCDC_SENSE}
- {pin_num: '77', pin_signal: VDD_SOC_IN_3, label: VDD_SOC_IN}
- {pin_num: '53', pin_signal: VDD_SOC_IN_2, label: VDD_SOC_IN}
- {pin_num: '15', pin_signal: DCDC_PSWITCH, label: MCU_DCDC_IN}
- {pin_num: '17', pin_signal: DCDC_IN_Q, label: MCU_DCDC_IN}
- {pin_num: '40', pin_signal: NVCC_PLL, label: VDDA_1P1_CAP}
- {pin_num: '27', pin_signal: RTC_XTALI, label: 'RTC_XTALI/Y2[1]'}
- {pin_num: '28', pin_signal: RTC_XTALO, label: 'RTC_XTALO/Y2[2]'}
- {pin_num: '29', pin_signal: USB_OTG1_VBUS, label: 5V_USB_OTG}
- {pin_num: '18', pin_signal: DCDC_IN, label: MCU_DCDC_IN}
- {pin_num: '19', pin_signal: DCDC_LP, label: DCDC_OUT}
- {pin_num: '34', pin_signal: NGND_KEL0, label: GND}
- {pin_num: '21', pin_signal: ONOFF, label: ONOFF}
- {pin_num: '25', pin_signal: VDD_SNVS_IN, label: VDD_SNVS_IN}
- {pin_num: '31', pin_signal: VDD_USB_CAP, label: VDD_USB_3V}
- {pin_num: '32', pin_signal: USB_OTG1_DN, label: OTG1_DN}
- {pin_num: '33', pin_signal: USB_OTG1_DP, label: OTG1_DP}
- {pin_num: '35', pin_signal: VDD_HIGH_CAP, label: VDDA_2P5_CAP}
- {pin_num: '42', pin_signal: VDDA_ADC_3P3/ADC_VREFH, label: VDDA_ADC_3P3_MCU/ADC_VREFH}
- {pin_num: '39', pin_signal: VDD_HIGH_IN, label: VDD_HIGH_IN_MCU}
- {pin_num: '22', pin_signal: POR_B, label: 'POR_B/RST_TGTMCU_B/J30[1]'}
- {pin_num: '37', pin_signal: XTALI, label: XTALI}
- {pin_num: '38', pin_signal: XTALO, label: XTALO}
- {pin_num: '10', pin_signal: GPIO_03, label: 'SAI1_RXD0/U10[16]', identifier: SAI1_RXD0}
- {pin_num: '9', pin_signal: GPIO_04, label: 'SAI1_TXD0/U10[14]', identifier: SAI1_TXD0}
- {pin_num: '8', pin_signal: GPIO_05, label: SAI1_TXD1, identifier: SAI1_TXD1}
- {pin_num: '6', pin_signal: GPIO_06, label: 'SAI1_TX_BCLK/U10[12]', identifier: SAI1_TX_BCLK}
- {pin_num: '5', pin_signal: GPIO_07, label: 'SAI1_TX_SYNC/U10[13]', identifier: SAI1_TX_SYNC}
- {pin_num: '4', pin_signal: GPIO_08, label: 'SAI1_MCLK/U10[11]', identifier: SAI1_MCLK}
- {pin_num: '59', pin_signal: GPIO_AD_01, label: 'ADC12_1/J26[10]/J56[14]', identifier: ADC12_1}
- {pin_num: '58', pin_signal: GPIO_AD_02, label: 'ADC12_2/J26[12]/J56[16]', identifier: ADC12_2}
- {pin_num: '57', pin_signal: GPIO_AD_03, label: 'LPSPI1_SDI/J57[10]/U27[2]', identifier: LPSPI1_SDI}
- {pin_num: '56', pin_signal: GPIO_AD_04, label: 'LPSPI1_SDO/J57[8]/U27[5]', identifier: LPSPI1_SDO}
- {pin_num: '55', pin_signal: GPIO_AD_05, label: 'LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1]', identifier: LPSPI1_PCS0}
- {pin_num: '52', pin_signal: GPIO_AD_06, label: 'LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6]', identifier: LPSPI1_SCK}
- {pin_num: '51', pin_signal: GPIO_AD_07, label: 'ADC12_3/J26[2]', identifier: ADC12_3}
- {pin_num: '13', pin_signal: GPIO_00, label: 'AUD_INT/U10[15]', identifier: AUD_INT}
- {pin_num: '80', pin_signal: GPIO_12, label: 'USB_OTG1_OC/U7[A2]', identifier: USB_OTG1_OC}
- {pin_num: '79', pin_signal: GPIO_13, label: 'USB_OTG1_ID/J9[4]/Q9[2]', identifier: USB_OTG1_ID}
- {pin_num: '60', pin_signal: GPIO_AD_00, label: USB_OTG1_PWR, identifier: USB_OTG1_PWR}
- {pin_num: '49', pin_signal: GPIO_AD_08, label: 'JTAG_TRSTB/J55[10]', identifier: JTAG_TRSTB}
- {pin_num: '48', pin_signal: GPIO_AD_09, label: 'ADC12_4/JTAG_TDO/J55[6]/J26[4]', identifier: ADC12_4}
- {pin_num: '47', pin_signal: GPIO_AD_10, label: 'ADC12_5/JTAG_TDI/J55[8]/J26[6]', identifier: ADC12_5}
- {pin_num: '46', pin_signal: GPIO_AD_11, label: WDOG_B/JTAG_MOD, identifier: WDOG_B}
- {pin_num: '45', pin_signal: GPIO_AD_12, label: 'JTAG_TCK/J55[4]', identifier: JTAG_TCK}
- {pin_num: '44', pin_signal: GPIO_AD_13, label: 'JTAG_TMS/J55[2]', identifier: JTAG_TMS}
- {pin_num: '43', pin_signal: GPIO_AD_14, label: 'ADC12_6/J26[8]', identifier: ADC12_6}
- {pin_num: '76', pin_signal: GPIO_SD_00, label: 'GPIO_SD_00/BT_CFG[2]', identifier: GPIO_SD_00}
- {pin_num: '75', pin_signal: GPIO_SD_01, label: 'GPIO_SD_01/BT_CFG[1]/TP31', identifier: GPIO_SD_01}
- {pin_num: '74', pin_signal: GPIO_SD_02, label: 'GPIO_SD_02/BT_CFG[0]/J57[2]/TP34', identifier: GPIO_SD_02}
- {pin_num: '73', pin_signal: GPIO_SD_03, label: 'GPIO_SD_03/BOOT_MODE[1]', identifier: GPIO_SD_03}
- {pin_num: '72', pin_signal: GPIO_SD_04, label: 'GPIO_SD_04/BOOT_MODE[0]', identifier: GPIO_SD_04}
- {pin_num: '61', pin_signal: GPIO_SD_13, label: 'GPIO_SD_13/BT_CFG[3]', identifier: GPIO_SD_13}
- {pin_num: '62', pin_signal: GPIO_SD_12, label: TP33}
- {pin_num: '24', pin_signal: PMIC_ON_REQ, label: PMIC_ON_REQ}
- {pin_num: '41', pin_signal: VSSA_ADC_3P3/ADC_VREFL, label: VDDA_ADC_3P3_MCU/ADC_VREFL/GND}
- {pin_num: '36', pin_signal: USB_OTG1_CHD_B, label: TP13}
power_domains: {NVCC_GPIO: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: LPUART1, signal: RXD, pin_signal: GPIO_09}
  - {pin_num: '2', peripheral: LPUART1, signal: TXD, pin_signal: GPIO_10}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_09_LPUART1_RXD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_10_LPUART1_TXD, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitQSPIPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '65', peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_10}
  - {pin_num: '66', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_09}
  - {pin_num: '68', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_07}
  - {pin_num: '67', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_08}
  - {pin_num: '64', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_11}
  - {pin_num: '69', peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_06}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitQSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitQSPIPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_06_FLEXSPI_A_SS0_B, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_07_FLEXSPI_A_DATA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_08_FLEXSPI_A_DATA2, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_09_FLEXSPI_A_DATA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_10_FLEXSPI_A_SCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_11_FLEXSPI_A_DATA3, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: GPIO1, signal: 'gpiomux_io, 11', pin_signal: GPIO_11, direction: OUTPUT, gpio_init_state: 'true', slew_rate: Slow, software_input_on: Disable,
    open_drain: Disable, drive_strength: R0_4, pull_keeper_select: Keeper, pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm, hysteresis_enable: Disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of GPIO_11 on GPIO_11 (pin 1) */
  gpio_pin_config_t GPIO_11_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_11 (pin 1) */
  GPIO_PinInit(GPIO1, 11U, &GPIO_11_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_11_GPIOMUX_IO11, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITLEDPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_SEL(0x00U)      
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_11_GPIOMUX_IO11, 0x10A0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '70', peripheral: GPIO2, signal: 'gpio_io, 05', pin_signal: GPIO_SD_05, direction: INPUT, gpio_interrupt: kGPIO_NoIntmode, slew_rate: Slow, software_input_on: Disable,
    open_drain: Disable, drive_strength: R0_4, pull_keeper_select: Pull, pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm, hysteresis_enable: Enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBUTTONPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of USER_BUTTON on GPIO_SD_05 (pin 70) */
  gpio_pin_config_t USER_BUTTON_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_05 (pin 70) */
  GPIO_PinInit(GPIO2, 5U, &USER_BUTTON_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_05_GPIO2_IO05, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITBUTTONPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_SEL(0x00U)      
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_05_GPIO2_IO05, 0x01B0A0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCOMBO_SENSORPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_02, slew_rate: Slow, software_input_on: Enable, open_drain: Enable, drive_strength: R0_4, pull_keeper_select: Keeper,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm, hysteresis_enable: Disable}
  - {pin_num: '12', peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_01, slew_rate: Slow, software_input_on: Enable, open_drain: Enable, drive_strength: R0_4, pull_keeper_select: Keeper,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm, hysteresis_enable: Disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCOMBO_SENSORPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCOMBO_SENSORPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_01_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_02_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_01_LPI2C1_SDA, 0xD8A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_02_LPI2C1_SCL, 0xD8A0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
